In [2]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [3]:
# We can randomly reorder (permutate) a Series, or the rows in a DataFrame

#Let's take a look
# Create a dataframe (0 - 15) or 16 point
# Reshape it to 4 by 4 matrix
dframe = DataFrame(np.arange(16).reshape((4, 4)))

#Create an array with a random perumation of 0,1,2,3
blender = np.random.permutation(4)

blender

array([1, 0, 2, 3])

In [4]:
# Show dataframe
# All rows in order
dframe

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [5]:
# Now permutate the dframe based on the blender
# The rows in the dataframe (0,1,2,3) will be reordered
# Based on the blender (1,0,2,3)
dframe.take(blender)

0   1   2   3
1   4   5   6   7
0   0   1   2   3
2   8   9  10  11
3  12  13  14  15

In [6]:
# Now what if we want permuations with replacement

In [7]:
# Let imagine a box with 3 marbles in it: labeled 1, 2, and 3
box = np.array([1,2,3])

# Now lets create a random permuation WITH replacement using randint
# Goes from 0 to size of box
shaker = np.random.randint(0, len(box), size=10)

In [8]:
# Show box
box

array([1, 2, 3])

In [10]:
# Let's check the box "shaker"
shaker

array([2, 0, 1, 0, 1, 2, 2, 2, 1, 1])

In [11]:
#Now lets grab form the box
hand_grabs = box.take(shaker)

#show
hand_grabs

array([3, 1, 2, 1, 2, 3, 3, 3, 2, 2])