In [4]:
import numpy as np

In [5]:
# Create an arrange where index starts at 0
arr = np.arange(0,11)

In [4]:
# Ouput array
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
# Call the value at index 8 in the array
arr[8]

8

In [7]:
# Call values indexed 1 to 5 in the array
arr[1:5]

array([1, 2, 3, 4])

In [8]:
# Call values indexed 0 to 5 in the array
arr[0:5]

array([0, 1, 2, 3, 4])

In [9]:
# Set the values from index 0 to 5 to 100 in the array
# leave the other values untouched
arr[0:5] = 100

In [10]:
# Output array
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
# Reset the array
arr = np.arange(0,11)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
# create a slice of the array
# 6 values
slice_of_arr = arr[0:6]

In [16]:
# Output array
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [17]:
# Change the slice that has 6 values
# All elements in that array = 99
# Output the slice of array
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [18]:
# The slice we created is a view of the array
# Any changes to that slice changes the original array
# Output original array
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [19]:
# Copy an array
# Output the copied array
# No arguments
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [7]:
# Indexing a 2D array
# Create a 3 by 3 2d array
# Output the array
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [13]:
# To index the array
# Output index row 0 (remember index start at 0)
arr_2d[0]

array([ 5, 10, 15])

In [14]:
arr_2d[1]

array([20, 25, 30])

In [16]:
arr_2d[2]

array([35, 40, 45])

In [17]:
arr_2d[0][0]

5

In [18]:
arr_2d[1][2]

30

In [19]:
#2d array slicing
# Show array
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [22]:
# Slice 2d array
# show everything up to index 2 row (index 0 and 1)
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [24]:
# Show all indexed rows up to 2
# Show all index columns from 1 onwards
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [25]:
# show bottom row
arr_2d[2]

array([35, 40, 45])

In [28]:
# Create a 10 by 10 all zero array
arr2d = np.zeros((10,10))

In [29]:
# Show array
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [32]:
# Get length of array - number of rows
arr_length = arr2d.shape[1]

In [33]:
# Show length - number of rows
arr_length

10

In [35]:
# For every i in the arr_length
# i is row number
# Which is 10 rows
# Set that element to 1
# Loop through each row
# Executes the arr2d[i] = 1 code ten times
for i in range(arr_length):
    arr2d[i]=1

In [36]:
arr2d

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [37]:
# For every i in the arr_length
# i is row number
# Which is 10 rows
# Set that element to i
# which is the row number
# Loop through each row
# Executes the arr2d[i] = i code ten times
for i in range(arr_length):
    arr2d[i]=i

In [38]:
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [42]:
#Show 2,4,6 8 index rows
arr2d[[2,4,6,8]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])

In [44]:
#Show 1,3,5,7,9 index rows
arr2d[[1,3,5,7,9]]

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])