In [1]:
# Import Numpy
import numpy as np


In [5]:
# Python rounds up when use division
10/3

3

In [6]:
# Need to add a decimal point
10.0/3

3.3333333333333335

In [7]:
# Can import from future
from __future__ import division

In [8]:
# Now Python doesn't round up
10/3

3.3333333333333335

In [9]:
# Create an array from two lists
arr1 = np.array([[1,2,3,4],[6,7,8,9]])

In [10]:
# Output array
arr1

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [11]:
# Multiply array by itself
arr1*arr1

array([[ 1,  4,  9, 16],
       [36, 49, 64, 81]])

In [12]:
# Multiply array by 2
arr1 * 2

array([[ 2,  4,  6,  8],
       [12, 14, 16, 18]])

In [13]:
# Divide array by 10
arr1 / 10

array([[ 0.1,  0.2,  0.3,  0.4],
       [ 0.6,  0.7,  0.8,  0.9]])

In [14]:
# Subtract from itself
arr1 - arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [15]:
# Subtract half itself from itself
arr1 - (arr1/2)

array([[ 0.5,  1. ,  1.5,  2. ],
       [ 3. ,  3.5,  4. ,  4.5]])

In [16]:
# Inverse array
1/arr1

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.16666667,  0.14285714,  0.125     ,  0.11111111]])

In [17]:
# Exponential operation
arr1 ** 3

array([[  1,   8,  27,  64],
       [216, 343, 512, 729]])