In [1]:
# Mathematical array functions
import numpy as np

In [4]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# Apply a square root of array elements
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [6]:
# Apply exponential
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [8]:
# binary functions need two arrar
# Create a random 10 element array
A = np.random.randn(10)
A

array([-0.32547952, -0.42334796, -0.87563259, -0.29829748, -0.40337934,
        1.20257342,  1.44665893,  0.09578126, -0.08277711, -0.95876391])

In [9]:
# Create another random 10 element array
B = np.random.randn(10)
B

array([ 0.90432405, -0.59099179, -0.69699796,  1.30223522, -1.14526556,
       -0.03124087,  1.20948555,  0.40806926,  1.57648596, -0.28312287])

In [10]:
# Binnary functions
# Add both arrays together
np.add(A,B)


array([ 0.57884453, -1.01433975, -1.57263056,  1.00393774, -1.5486449 ,
        1.17133255,  2.65614448,  0.50385052,  1.49370885, -1.24188678])

In [11]:
# Apply maxumum to comparative elements in boith arrays
np.maximum(A,B)

array([ 0.90432405, -0.42334796, -0.69699796,  1.30223522, -0.40337934,
        1.20257342,  1.44665893,  0.40806926,  1.57648596, -0.28312287])

In [12]:
np.minimum(A,B)

array([-0.32547952, -0.59099179, -0.87563259, -0.29829748, -1.14526556,
       -0.03124087,  1.20948555,  0.09578126, -0.08277711, -0.95876391])

In [1]:
# Show list of universal functioins in numpy from scipy website
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html'
import webbrowser
webbrowser.open(website)
    

True